---
# OpenShift Local installation won't appear in the OpenShift Cluster Manager unless you enable cluster monitoring and telemetry.

- name: Set configuration properties
  command: "crc config set {{ item }}"
  with_items: 
    - "consent-telemetry yes"
    - "enable-cluster-monitoring false"
    - "cpus 5"
    - "memory 14305"
    - "pull-secret-file ~/Downloads/pull-secret.txt"
    - "preset {{ crc_preset }}"

# Prepare and create ~/.crc directory if not already existing
- name: Set up local virtualization and networking infrastructure
  command: crc setup

- name: Display configuration
  command: crc config view
