---
# Install / Upgrade the CRC command line tool

- name: Download crc package
  get_url:
    url: "{{ crc_download_url }}"
    dest: "{{ crc_package }}"

- name: Install crc package [Mac OS]
  shell: "installer -pkg {{ crc_package }} -target '{{ crc_macos_volume }}'"
  when: ansible_os_family == "Darwin"
  become: true

# Ensure location /usr/local/bin/crc
#$ which crc

# Check software versions
#$ hyperkit -version
#$ crc version
